# Generated by Django 5.2.13 on 2026-04-23 14:29

from django.db import migrations
from dotenv import load_dotenv
from django.contrib.auth.hashers import make_password
import os

load_dotenv()

def load_initial_data(apps,schema_editor):
    #creating intitial data for admin
    Role = apps.get_model('user_mgmt','Role')
    Department = apps.get_model('user_mgmt','Department')
    Employee = apps.get_model('user_mgmt','Employee')
    
    super_admin_role = Role.objects.create(name='super-admin')
    admin_department = Department.objects.create(name='Admin')
    admin = Employee.objects.create(
        email=os.getenv('admin_mail'),
        password=make_password(os.getenv('admin_pass')),
        role=super_admin_role,
        department=admin_department,
        first_name='MVP',
        last_name='SuckerGOAT',
        is_superuser=True,
        is_staff=True
    )

def reverse_load_initial_data(apps,schema_editor):
    #removing intial data
    Role = apps.get_model('user_mgmt','Role')
    Department = apps.get_model('user_mgmt','Department')
    Employee = apps.get_model('user_mgmt','Employee')
    
    super_admin_role = Role.objects.get(name='super-admin')
    admin_department = Department.objects.get(name='Admin')
    admin = Employee.objects.get(email=os.getenv('admin_mail'))
    
    if admin is not None:
        admin.delete()
    if super_admin_role is not None:
        super_admin_role.delete()
    if admin_department is not None:
        admin_department.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data,reverse_load_initial_data)
    ]