# Generated by Django 5.2.13 on 2026-04-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='hr_id',
            new_name='hr',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='mngr_id',
            new_name='mngr',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='reporting_mngr_id',
            new_name='reporting_mngr',
        ),
    ]
