# Generated by Django 5.2.13 on 2026-04-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_rename_hr_id_department_hr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='mngr',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='reporting_mngr',
            new_name='reporting_manager',
        ),
    ]
