# Generated by Django 5.2.13 on 2026-04-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0004_role_alter_department_options_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
