# Generated by Django 5.2.13 on 2026-04-27 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('given_days', models.IntegerField()),
                ('leave_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('compensation', 'Compensation'), ('incident', 'Incident')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Leave Policies',
                'db_table': 'leavepolicy',
            },
        ),
        migrations.CreateModel(
            name='LeaveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('compensation', 'Compensation'), ('incident', 'Incident')], max_length=15)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('pen', 'Pending'), ('apr', 'Approved')], max_length=10)),
                ('reason', models.CharField(max_length=250)),
                ('approved_by', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leaves',
                'db_table': 'leavelog',
            },
        ),
    ]
