# Generated by Django 5.2.13 on 2026-04-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0003_alter_leavelog_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('compensation', 'Compensation'), ('incident', 'Incident')], max_length=15, unique=True),
        ),
    ]
