# Generated by Django 5.2.13 on 2026-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0004_alter_leavepolicy_leave_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavelog',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'Leaves'},
        ),
        migrations.AlterModelOptions(
            name='leavepolicy',
            options={'ordering': ['name'], 'verbose_name_plural': 'Leave Policies'},
        ),
        migrations.RenameField(
            model_name='leavelog',
            old_name='approved_by',
            new_name='actioned_by',
        ),
        migrations.AddField(
            model_name='leavelog',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leavelog',
            name='status',
            field=models.CharField(blank=True, choices=[('pen', 'Pending'), ('apr', 'Approved'), ('rej', 'Rejected')], default='pen', max_length=10, null=True),
        ),
    ]
