# Generated by Django 5.2.13 on 2026-04-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0005_alter_leavelog_options_alter_leavepolicy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavelog',
            name='reason',
        ),
    ]
